### ISSUE TITLE
Replication study inspired by Steinmann et al 2022

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/PaleoBooks#12]
1. Goal: Hydroclimate PaMoDaCo over the neotropics Last Millennium
2. Description:  Use the PRECIPd18O data from [Steinmann et al 2022](https://doi.org/10.1073/pnas.2120015119), load into pyleo EnsembleSeries, run MC-PCA and compare to [iCESM](https://www2.cesm.ucar.edu/models/cesm1.2/) last millennium simulation (available [here](https://fzhu2e.github.io/cfr/notebooks/climate-io.html) and maybe through globus).  The idea would be to showcase how to access paleo obs and model data and run a fairly complex (age-aware) analysis and reproduce something that looks like one of the figures in the paper. 
3. References/data sources: [Steinmann et al 2022](https://doi.org/10.1073/pnas.2120015119), [iCESM](https://www2.cesm.ucar.edu/models/cesm1.2/) 
4. Keywords (science): hydroclimate, MC-PCA
5. Keywords (tech): pangeo-forge, ARCO data, globus

**Comment by CommonClimate** [comment]
Data can be found [here](https://www.earthsystemgrid.org/dataset/ucar.cgd.ccsm4.cesmLME.atm.proc.monthly_ave.PRECSC_H218Os.html). @fzhu2e do you know how to turn those fields to d18O? How did you do that for the data you archived as part of `cfr`?

**Comment by fzhu2e** [comment]
> Data can be found [here](https://www.earthsystemgrid.org/dataset/ucar.cgd.ccsm4.cesmLME.atm.proc.monthly_ave.PRECSC_H218Os.html). @fzhu2e do you know how to turn those fields to d18O? How did you do that for the data you archived as part of `cfr`?

Hi Julien, here's the recipe:
```
        p16O = ds['PRECRC_H216Or'] + ds['PRECSC_H216Os'] + ds['PRECRL_H216OR'] + ds['PRECSL_H216OS']
        p18O = ds['PRECRC_H218Or'] + ds['PRECSC_H218Os'] + ds['PRECRL_H218OR'] + ds['PRECSL_H218OS']

        p16O = p16O.where(p16O > 1e-18, 1e-18)
        p18O = p18O.where(p18O > 1e-18, 1e-18)

        d18Op = (p18O / p16O - 1)*1000
```

**Comment by CommonClimate** [comment]
Most excellent! Thank you so much for the trick. Immensely helpful!

**Comment by khider** [comment]
One problem with this: data size. Each text file is around 200-500MB because of the age models. I propose we use the median age model for the cookbook so we can get a smaller file. 

We may need to have a "smaller" example (i.e., less proxy) to do MC-PCA. Thoughts?

**Comment by CommonClimate** [comment]
yes, we can streamline on a subset of proxies, or maybe a subset of the age ensembles?

**Comment by khider** [comment]
I'm going to do median for the Pythia Cookbook and we can figure out how to store the data in LiPD and on the graphDB later on.

**Comment by khider** [comment]
@fzhu2e Trying to figure out the numbering system at NCAR?

<img width="876" alt="image" src="https://github.com/LinkedEarth/PaleoBooks/assets/11758571/163492b3-3629-4a9c-9ab3-3dfd203565e5">

Which one corresponds to the all forcing?

**Comment by khider** [comment]
Done for Project Pythia. Needs to be included in our gallery

https://github.com/ProjectPythia/paleoPCA-Cookbook

**Comment by khider** [comment]
PaleoPCA notebook into Pythia and LinkedEarth galleries
