### ISSUE TITLE
Please add contributions from the Pyleoclim Paper to the gallery

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PaleoBooks#13]
Please note: before filling out this template, make sure that your JupyterBook is built and published.

1. Name of the repository: PyleoclimPaper
2. Repo url: https://github.com/LinkedEarth/PyleoclimPaper
3. Host for the JupyterBook: https://linkedearth.github.io
4. User: linkedearth
5. Landing suffix (name of the page you want users to land on): README.html

**Comment by jordanplanders** [comment]
@khider Thanks for the submission! Your book has been added to the gallery!
