### ISSUE TITLE
Submit this repo to your gallery

### ISSUE THREAD

**Issue by khider** [LinkedEarth/PaleoBooks#6]
Please note: before filling out this template, make sure that your JupyterBook is built and published.

1. Name of the repository:  DISK-proxyComposite
2. Repo url: https://github.com/khider/DISK-proxyComposite
3. Host for the JupyterBook: https://khider.github.io
4. User: khider
5. Landing suffix (name of the page you want users to land on): intro.html

**Comment by jordanplanders** [comment]
@khider I think we tied this up, yes?

**Comment by khider** [comment]
Yes! I'll let you have the honor to close this one.
