### ISSUE TITLE
Request to include LERM notebooks in paleobooks

### ISSUE THREAD

**Issue by alexkjames** [LinkedEarth/PaleoBooks#8]
Please note: before filling out this template, make sure that your JupyterBook is built and published.

1. Name of the repository: Detecting_Paleoclimate_Transitions_with_LERM
2. Repo url: https://github.com/alexkjames/Detecting_Paleoclimate_Transitions_with_LERM
3. Host for the JupyterBook: https://alexkjames.github.io
4. User: alexkjames
5. Landing suffix (name of the page you want users to land on): intro.html

**Comment by khider** [comment]
Done!
